### PR TITLE
Update snippet.formitisselected.php

### PR DESCRIPTION
**Pull request by bertoost**
Fixed error when $input not is an array

### CODE REVIEW

**Comment by bertoost** [comment]
When is this going to be merged?? Really annoying I every time get that error (and others too probably?)

**Comment by jpdevries** [comment]
Got this merged in the new modxcms/FormIt fork
https://github.com/modxcms/FormIt/commit/44edb50fb3b5b87781f1b1e827956017fe2ec340

**Comment by CyntaxDotDev** [comment]
Wasn't in the most recent update however, still looking forward to that specific update...

**Comment by pixelchutes** [comment]
:+1:

**Comment by jpdevries** [comment]
Will look into where FormIt is at today. After releasing Gallery-1.6 prematurely, always looking for testers to help test out releases before they go public. will see if latest beta is still up to date

**Pull request merged**
